apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
  - protocol: TCP
    port: 3000  # Service port
    targetPort: 3000  # Pod port
    nodePort: 30000  # External port (30000-32767 range)
  type: NodePort  # Exposes on node IP (minikube tunnel forwards to localhost:30000)